### PR TITLE
Support multiple private repositories

### PR DESCRIPTION
**Pull request by ymkjp**
Hi, thanks for your great docker receipt.

I think it would be better if we could let satis host to handle multiple private repos.

### CODE REVIEW

**Comment by ypereirareis** [comment]
Hi !
Thanks for this PR ! it could be useful indeed.
Once tested, I'll merge it if everyting is fine !
Thx !

**Comment by ypereirareis** [comment]
Actually we could only deal with `PRIVATE_REPO_DOMAIN_LIST` variable and use it to pass one or more URLs. So the old variable is useless.

**Comment by ymkjp** [comment]
Hmm, sounds strange.

How did you try it?

It should be like:

``` bash
# Correct
-e PRIVATE_REPO_DOMAIN_LIST="foo.example.com bar.example.net"
```

Not like:

``` bash
# Incorrect
-e PRIVATE_REPO_DOMAIN_LIST="foo.example.com"
-e PRIVATE_REPO_DOMAIN_LIST="bar.example.net"
```

**Comment by ypereirareis** [comment]
No don't worry I DID NOT test it yet !:smile:

"_**Once tested**, I'll merge it if everyting is fine !_"

**Comment by ymkjp** [comment]
Oh, my bad.
I misread it.

I think you better to keep the old variable for backward compatibility.

**Comment by ypereirareis** [comment]
Yes you're right ! But this repo is more and more used by people so I'm gonna start a semver versioning and a changelog file. I'll add a warning message in the `startup.sh` to tell people which tag to use to get the old working version.

**Comment by ypereirareis** [comment]
OK!
- I integrated your dev  while updating the image, the changelog and the release process => So I close your PR but thx a lot.
- I introduced a BC so use the version `ypereirareis/docker-satis:1.0.0` of the image to use `PRIVATE_REPO_DOMAIN` and `ypereirareis/docker-satis:2.0.0` to use `PRIVATE_REPO_DOMAIN_LIST`
- The latest tag will always be a master build now !

**Docker hub autobuild is in progress !**

**Pull request closed without merging**
